"""
공통 설정/외부 의존성 모듈.

주의:
- 이 파일은 .env 로딩과 운영 안정화(improvements) 연결만 담당합니다.
- 텔레그램 핸들러 로직은 각 기능 모듈로 분리했습니다.
"""
import os
from pathlib import Path
import asyncio
import re
import csv
import tempfile
import uuid
import unicodedata
from difflib import SequenceMatcher
from datetime import datetime, timedelta

from dotenv import load_dotenv
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import (
    ApplicationBuilder,
    CommandHandler,
    MessageHandler,
    ContextTypes,
    CallbackQueryHandler,
    filters,
)

import pandas as pd

from plan_product_change import is_product_change_question, handle_product_change_question
from ai_parser import parse_question
from inventory_engine import check_production, build_result, find_similar_products, BOM_FILE
from purchase_order import is_purchase_request_question, create_purchase_request_from_result
from purchase_order_form import is_purchase_order_form_question, create_purchase_order_excel
from date_utils import parse_production_date
from production_memory import (
    format_plan_list,
    delete_production_plan,
    load_plans,
    save_plans,
    normalize_plan_date,
    parse_plan_date,
    get_product_info,
    fmt_num,
    add_production_plan,
    update_production_plan,
    get_planned_consumption_until,
)
from multi_plan import is_multi_production_request, handle_multi_production_request, parse_multi_items
from summary_commands import (
    is_plan_shortage_summary_question,
    is_shortage_excel_question,
    handle_plan_shortage_summary,
    handle_shortage_excel,
)

from contract_production import (
    parse_contract_text,
    add_contract_rule,
    format_contract_list,
    delete_contract,
    simulate_contracts,
    convert_contract_month_to_plan,
)

from plan_natural_change import (
    is_plan_natural_change_text,
    update_plan_by_natural_change,
)

from reserved_production_plan import (
    is_reserved_plan_user,
    is_reserved_register_text,
    is_reserved_plan_explicit_text,
    add_reserved_plan_from_text,
    format_reserved_plan_list,
    delete_reserved_plan,
    convert_reserved_to_actual,
)

from ocr_product_memory import (
    lookup_ocr_product_memory,
    remember_ocr_product,
    forget_ocr_product_memory,
    format_ocr_product_memory,
)

from group_chat_filter import (
    should_process_group_message,
    should_reply_unauthorized,
)

from force_register_mode import (
    apply_force_mode_command,
    get_force_mode_status_text,
    is_force_enabled_for_date,
)

try:
    from image_parser import extract_questions_from_image
    PHOTO_SUPPORT = True
except Exception:
    extract_questions_from_image = None
    PHOTO_SUPPORT = False


load_dotenv()

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
ALLOWED_USER_IDS = os.getenv("ALLOWED_USER_IDS", "")
ADMIN_USER_IDS = os.getenv("ADMIN_USER_IDS", "")

if not TELEGRAM_BOT_TOKEN:
    raise RuntimeError("TELEGRAM_BOT_TOKEN이 .env 파일에 없습니다.")

BOT_VERSION = "plan-manage-v9-photo-continue-20260613"

# ===== 운영 안정화 추가 블록: generated by apply_improvements.py =====
from pathlib import Path as _ImprovedPath

_ImprovedPath("logs").mkdir(exist_ok=True)
_ImprovedPath("backups").mkdir(exist_ok=True)

try:
    from improvements.handlers import (
        whoami_command as _improved_whoami_command,
        status_command as _improved_status_command,
        backup_command as _improved_backup_command,
        logs_command as _improved_logs_command,
        global_error_handler as _improved_global_error_handler,
    )
    from improvements.safe_io import backup_many as _improved_backup_many
except Exception:
    _improved_whoami_command = None
    _improved_status_command = None
    _improved_backup_command = None
    _improved_logs_command = None
    _improved_global_error_handler = None
    _improved_backup_many = None


def _improved_backup_known_data_files(reason="before_change"):
    if _improved_backup_many is None:
        return []
    files = [
        os.getenv("BOM_FILE", "bom.xlsx"),
        os.getenv("STOCK_FILE", "stock.xlsx"),
        os.getenv("PRODUCTION_PLAN_FILE", "production_plans.xlsx"),
    ]
    return _improved_backup_many(files, backup_dir="backups", reason=reason)
